### ISSUE TITLE
Patrocinador Plata

### ISSUE THREAD

**Issue by howserlx** [desarrolladorSLP/tunatech-website#12]
Colocar a UXMALSOFT como patrocinador Plata
https://uxmalsoft.com/

**Comment by iuresti** [comment]
Añadí uxmalsoft a la sección de patrocinadores pero desconozco si se hace algo especial dependiendo del nivel.

**Comment by howserlx** [comment]
Solo es en efectivo, les coparto el documento de patrocinios
@iuresti podrías poner mejor el logo vertical porfa
https://drive.google.com/file/d/1mkkEiP6NVCWKG8y9yS3KkyJLUdOPOKjd/view?usp=sharing

**Comment by iuresti** [comment]
Hecho.
Con respecto al nivel, me refiero si el patrocinador se ve diferente en la página dependiendo del nivel?

**Comment by howserlx** [comment]
La liga del enlace debe estar para abrir en pestaña nueva como los demás
